spring.application.name=finances
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_database
spring.datasource.username=admin
spring.datasource.password=12345678

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=MYJWTSECRET
jwt.expiration=3600000