spring.application.name=finances

# Configuração temporária enquanto o ambiente do PostgreSQL não foi definido.
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration